# Generated by Django 4.1.2 on 2022-11-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newvieuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='language',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='streamingoption',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='last_name',
            field=models.CharField(default='Appleseed', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(to='app.cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(to='app.language'),
        ),
        migrations.AddField(
            model_name='movie',
            name='streaming_options',
            field=models.ManyToManyField(blank=True, to='app.streamingoption'),
        ),
    ]
