# Generated by Django 4.1.2 on 2022-11-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cast_movie_remove_cast_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime_length',
            field=models.TimeField(),
        ),
    ]
