# Generated by Django 4.1.2 on 2022-11-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_movie_runtime_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
